### ISSUE TITLE
Get side menu notification badge to display on History tab icon and MR button in side menu

### ISSUE THREAD

**Issue by brenmous** [brenmous/peak-performance#11]

**Comment by bjchiong** [comment]
I'll work on this. History badge should show a different counter right? It notifies what was completed.

**Comment by brenmous** [comment]
I thought it was for incomplete reviews but whatever you think is best, UI is your call

**Comment by bjchiong** [comment]
Yeah. I don't feel like the history summary needs to show any notification. It works better to notify them in the menu and slide menu for MR.
