### ISSUE TITLE
The app crashes after logging in a newly signed up account (unexpectedly unwrap an optional error' after fetching the summary for initial setup)

### ISSUE THREAD

**Issue by bjchiong** [brenmous/peak-performance#12]
The app crashes after logging in a newly signed up account. The console prints out 'unexpectedly unwrap an optional error' after fetching the summary for initial setup. Other old user accounts still work.

**Comment by brenmous** [comment]
Fixed - loading new properties from database that old accounts don't have. I'm going to go through the data service and do a check on every value when we do our final clean up.
