### ISSUE TITLE
App doesn't prompt for media access in dreamlist

### ISSUE THREAD

**Issue by JoelBouka** [brenmous/peak-performance#17]
When clicking on camera roll when adding a dream, the app does not prompt the user to allow access. Only the placeholder shows telling them to go to their privacy settings to enable there.

**Comment by brenmous** [comment]
Are you still on iOS 9? That pop up is automatically provided and it works on the simulator still but we found with Ben H's phone on iOS 10 that a pop up doesn't show and that we had to provide that message.

**Comment by JoelBouka** [comment]
Yes still on iOS 9, had to go through the privacy settings to get the dreamlist working.

**Comment by brenmous** [comment]
I'll dig around, see if there's a way to get that pop-up to show
