### ISSUE TITLE
initial review summary cannot be viewed after initial setup

### ISSUE THREAD

**Issue by bjchiong** [brenmous/peak-performance#20]

**Comment by brenmous** [comment]
There's no view or view controller for it.

**Comment by brenmous** [comment]
Feel free to make one yourself otherwise if you've got the prototype I can do it tonight

**Comment by bjchiong** [comment]
No worries, ill set it up. Pretty much the same as the vc on the initial setup.

**Comment by brenmous** [comment]
Cheers Ben, yeah same pattern
